/*
 * Copyright 2019 yorlysoro.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package BDA;
import luncheria.basedatos;
import VALIDACION.limitar;
import VALIDACION.Validacion;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author giovanni
 */
public class ConfigurarPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurarPreguntas
     */
    private String cedula;
    private basedatos bd;
    private Validacion valid;
    private JTextField[] lcampos = new JTextField[2];
    public ConfigurarPreguntas(String cedula, basedatos bd) {
        this.bd = bd;
        this.cedula = cedula;
        this.valid = new Validacion();
        

        initComponents();
        this.lcampos[0] = txtRpt1;
        this.lcampos[1] = textRpt2;
        this.comboPgt1.requestFocus();
        this.setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPgt1 = new javax.swing.JComboBox<>();
        txtRpt1 = new javax.swing.JTextField();
        comboPgt2 = new javax.swing.JComboBox<>();
        textRpt2 = new javax.swing.JTextField();
        lblAnuncio = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Configure sus preguntas de seguridad");
        setFocusTraversalPolicyProvider(true);
        setType(java.awt.Window.Type.POPUP);

        comboPgt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cual es su pasatiempo favorito?", "¿Estado donde nacio su madre?", " " }));

        txtRpt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRpt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRpt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRpt1KeyTyped(evt);
            }
        });

        comboPgt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cual es el segundo nombre de su madre?", "¿Nombre de su materia favorita en la escuela?" }));

        textRpt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textRpt2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textRpt2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textRpt2KeyTyped(evt);
            }
        });

        lblAnuncio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnuncio.setText("Configure sus Preguntas de Seguridad");

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboPgt1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboPgt2, 0, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textRpt2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(txtRpt1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(lblAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblAnuncio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPgt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRpt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPgt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRpt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.bd.Conectar();
        String preguntas[] = new String[4];
        preguntas[0] = String.valueOf(this.comboPgt1.getSelectedItem());
        preguntas[1] = this.txtRpt1.getText();
        preguntas[2] = String.valueOf(this.comboPgt2.getSelectedItem());
        preguntas[3] = this.textRpt2.getText();
        
        try{
            String Consulta = "INSERT INTO preguntas_seguridad(Cedula_empleado, Pregunta, Respuesta) "
                + " VALUES( '" +  this.cedula + "', '" +  preguntas[0] + "', '" + preguntas[1] + "' ) " ;
            this.bd.setStm(Consulta);
            Consulta = "INSERT INTO preguntas_seguridad(Cedula_empleado, Pregunta, Respuesta) "
                + " VALUES( '" +  this.cedula + "', '" +  preguntas[2] + "', '" + preguntas[3] + "' ) " ;
            this.bd.setStm(Consulta);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error al guardar las preguntas: " + e);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.txtRpt1.setText("");
        this.textRpt2.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtRpt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRpt1KeyTyped
        // TODO add your handling code here:
        if(this.txtRpt1.getText().length() == limitar.fulltext)
            evt.consume();
      
    }//GEN-LAST:event_txtRpt1KeyTyped

    private void txtRpt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRpt1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
            this.textRpt2.requestFocus();
        if(this.valid.campos(lcampos) && this.textRpt2.getText().length() > 0)
            this.btnGuardar.setEnabled(true);
        if(!this.valid.campos(lcampos) || this.textRpt2.getText().equalsIgnoreCase(""))
            this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtRpt1KeyPressed

    private void txtRpt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRpt1KeyReleased
        // TODO add your handling code here:
         if(this.valid.campos(lcampos) && this.textRpt2.getText().length() > 0)
            this.btnGuardar.setEnabled(true);
        else if(!this.valid.campos(lcampos) || this.textRpt2.getText().equalsIgnoreCase(""))
            this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtRpt1KeyReleased

    private void textRpt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRpt2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER && this.valid.campos(lcampos) )
            this.btnGuardarActionPerformed(null);
        if(this.valid.campos(lcampos) && this.txtRpt1.getText().length() > 0)
            this.btnGuardar.setEnabled(true);
        if(!this.valid.campos(lcampos) || this.txtRpt1.getText().equalsIgnoreCase(""))
            this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_textRpt2KeyPressed

    private void textRpt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRpt2KeyTyped
        // TODO add your handling code here:
          if(this.textRpt2.getText().length() == limitar.fulltext)
            evt.consume();
    }//GEN-LAST:event_textRpt2KeyTyped

    private void textRpt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textRpt2KeyReleased
        // TODO add your handling code here:
        if(this.valid.campos(lcampos) && this.txtRpt1.getText().length() > 0)
            this.btnGuardar.setEnabled(true);
        if(!this.valid.campos(lcampos) || this.txtRpt1.getText().equalsIgnoreCase(""))
            this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_textRpt2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboPgt1;
    private javax.swing.JComboBox<String> comboPgt2;
    private javax.swing.JLabel lblAnuncio;
    private javax.swing.JTextField textRpt2;
    private javax.swing.JTextField txtRpt1;
    // End of variables declaration//GEN-END:variables
}
