/*
 * Copyright 2019 yorlysoro.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package BDA;
import VALIDACION.Validacion;
import VALIDACION.limitar;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import luncheria.basedatos;
import net.sf.jasperreports.engine.util.DigestUtils;
import org.apache.commons.codec.digest.DigestUtilsTest;


/**
 *
 * @author Jerrinson
 */
public class OlvidoContrasena extends javax.swing.JFrame {
    
    /**
     * Creates new form OlvidoContrasena
     */
    private basedatos bd;
    String[] Respuestas = new String[2];
    VALIDACION.Validacion valid;
    public OlvidoContrasena(basedatos bd) {
        this.bd = bd;
        this.valid = new VALIDACION.Validacion();
        initComponents();
        this.valid.SNumeros(txtCedula);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrg1 = new javax.swing.JLabel();
        txtPgt1 = new javax.swing.JTextField();
        lblPrg2 = new javax.swing.JLabel();
        txtPgt2 = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        lblVerifContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        txtVerifContrasena = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("¿Olvido su contraseña?");

        lblPrg1.setText("Pregunta1");

        txtPgt1.setEditable(false);
        txtPgt1.setEnabled(false);
        txtPgt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPgt1ActionPerformed(evt);
            }
        });
        txtPgt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPgt1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPgt1KeyTyped(evt);
            }
        });

        lblPrg2.setText("Pregunta2");

        txtPgt2.setEditable(false);
        txtPgt2.setEnabled(false);
        txtPgt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPgt2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPgt2KeyTyped(evt);
            }
        });

        lblContrasena.setText("Contraseña");

        lblVerifContrasena.setText("Verificar Contraseña");

        txtContrasena.setEditable(false);
        txtContrasena.setEnabled(false);
        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyPressed(evt);
            }
        });

        txtVerifContrasena.setEditable(false);
        txtVerifContrasena.setEnabled(false);
        txtVerifContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVerifContrasenaKeyPressed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lblCedula.setText("Cedula");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setEnabled(false);

        btnConsultar.setText("Consultar");
        btnConsultar.setEnabled(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(345, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblContrasena)
                                .addComponent(lblVerifContrasena)
                                .addComponent(lblPrg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblCedula))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPgt2)
                                    .addComponent(txtContrasena)
                                    .addComponent(txtVerifContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                .addComponent(txtPgt1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(btnConsultar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCedula)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrg1)
                    .addComponent(txtPgt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrg2)
                    .addComponent(txtPgt2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVerifContrasena)
                    .addComponent(txtVerifContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPgt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPgt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPgt1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER && this.txtCedula.getText().length() > 0 && !this.txtCedula.getText().equalsIgnoreCase("")){
            this.btnBuscar.setEnabled(true);
            this.buscar();
        }
        if(this.txtCedula.getText().length() > 0)
            this.btnBuscar.setEnabled(true);
        else
            this.btnBuscar.setEnabled(false);
    
    }//GEN-LAST:event_txtCedulaKeyPressed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        if(this.txtCedula.getText().length() == VALIDACION.limitar.cedula)
            evt.consume();
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtPgt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPgt1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
            this.txtPgt2.requestFocus();
    }//GEN-LAST:event_txtPgt1KeyPressed

    private void txtPgt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPgt1KeyTyped
        // TODO add your handling code here:
        if(this.txtPgt1.getText().length() == VALIDACION.limitar.fulltext)
            evt.consume();
    }//GEN-LAST:event_txtPgt1KeyTyped

    private void txtPgt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPgt2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER && this.txtPgt1.getText().length() > 0 && this.txtPgt1.getText().equalsIgnoreCase("") && this.txtPgt2.getText().length() > 0 && this.txtPgt2.getText().equalsIgnoreCase("")){
            this.btnConsultar.setEnabled(true);
            this.consultar();
        }
        if(this.txtPgt1.getText().length() > 0 && this.txtPgt2.getText().length() > 0)
            this.btnConsultar.setEnabled(true);
       else
            this.btnConsultar.setEnabled(true);
    }//GEN-LAST:event_txtPgt2KeyPressed

    private void txtPgt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPgt2KeyTyped
        // TODO add your handling code here:
        if(this.txtPgt2.getText().length() == VALIDACION.limitar.fulltext)
            evt.consume();
    }//GEN-LAST:event_txtPgt2KeyTyped

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        this.consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER)
            this.txtVerifContrasena.requestFocus();
    }//GEN-LAST:event_txtContrasenaKeyPressed

    private void txtVerifContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerifContrasenaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER && this.valid.cmpr_contrasenas(this.txtContrasena.getPassword(), this.txtVerifContrasena.getPassword())){
            this.btnGuardar.setEnabled(true);
            this.guardar();
        }
        if(this.txtContrasena.getPassword().length > 0 && this.txtVerifContrasena.getPassword().length > 0)
            this.btnGuardar.setEnabled(true);
        else
            this.btnGuardar.setEnabled(false);
    }//GEN-LAST:event_txtVerifContrasenaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblPrg1;
    private javax.swing.JLabel lblPrg2;
    private javax.swing.JLabel lblVerifContrasena;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtPgt1;
    private javax.swing.JTextField txtPgt2;
    private javax.swing.JPasswordField txtVerifContrasena;
    // End of variables declaration//GEN-END:variables

    private void buscar() {
        this.bd.Conectar();
        try {
            this.bd.setResult("SELECT cedula FROM empleados WHERE cedula = '" + this.txtCedula.getText() + "'");
            ResultSet result = this.bd.getResult();
            if(result.next()){
              this.bd.setResult("SELECT Pregunta, Respuesta FROM preguntas_seguridad WHERE Cedula_empleado = '" + this.txtCedula.getText() + "'");
              result = this.bd.getResult();
              String[] Preguntas = new String[2];
              
              int i = 0;
              while(result.next()){
                  Preguntas[i] = result.getString(1);
                  this.Respuestas[i] = result.getString(2);
                  i++;
              }
              this.lblPrg1.setText(Preguntas[0]);
              this.lblPrg2.setText(Preguntas[1]);
              this.txtPgt1.setEditable(true);
              this.txtPgt1.setEnabled(true);
              this.txtPgt2.setEditable(true);
              this.txtPgt2.setEnabled(true);
              this.txtPgt1.requestFocus();
              
            }else{
                JOptionPane.showMessageDialog(null, "No existe la cedula ingresada!!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OlvidoContrasena.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void guardar() {
        String Contrasena = Encriptacion.Encriptar(String.valueOf(this.txtContrasena.getPassword()));
        
        this.bd.Conectar();
        try {
            this.bd.setStm("UPTADE usuarios SET contrasena = '" + Contrasena +"' WHERE cedula_empleado = '" + this.txtCedula.getText() + "' ");
        } catch (SQLException ex) {
            Logger.getLogger(OlvidoContrasena.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        
        
    }

    private void consultar() {
        if(this.txtPgt1.getText().equalsIgnoreCase(this.Respuestas[0]) && this.txtPgt2.getText().equalsIgnoreCase(this.Respuestas[1])){
            this.txtContrasena.setEditable(true);
            this.txtContrasena.setEnabled(true);
            this.txtVerifContrasena.setEditable(true);
            this.txtVerifContrasena.setEnabled(true);
            this.txtContrasena.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null, "Las respuestas no son las correctas!!");
        }
    }
}
