/*
 * Copyright 2019 yorlysoro <yorlysoro@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package luncheria;

import VALIDACION.Validacion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Formatter;
import java.util.FormatterClosedException;
import java.util.NoSuchElementException;
import java.util.Scanner;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import BDA.Respaldo;

/**
 *Ventana Configuracion
 * Esta ventana se encargar de leer y cargar en un archivo toda la informacion correspondiente
 * a la conexion con la base de datos, por medio de dos funciones Llamadas Leer y Guardar
 * @author giovanni
 */
public class Configuracion extends javax.swing.JFrame {

    private Formatter Config;
    private Scanner entrada;

    /**
     * Creates new form Configuracion
     */
    /**
     * Constructor de la ventana configuracion
     */
    public Configuracion() {
        initComponents();
        this.setLocationRelativeTo(null);
        BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Iniciando la ventana de configuracion");
        lcampos[0] = txtNombre;
        lcampos[1] = txtHost;
        lcampos[2] = txtUsuario;
        lcampos[3] = txtPuerto;
        
        SNumeros(txtPuerto);
        SLetras(txtNombre);
        Leer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabBD = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblHost = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtHost = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbPuerto = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtArchivo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalir2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtArchivo1 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        btnGuardar2 = new javax.swing.JButton();
        btnSalir3 = new javax.swing.JButton();

        setTitle("Configuracion");
        setBackground(new java.awt.Color(255, 255, 255));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setUndecorated(true);
        setResizable(false);

        tabBD.setBackground(new java.awt.Color(51, 153, 255));
        tabBD.setForeground(new java.awt.Color(0, 102, 204));
        tabBD.setToolTipText("Aqui se realiza la configuracion de la base de datos");
        tabBD.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        tabBD.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        lblNombre.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblHost.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblHost.setForeground(new java.awt.Color(255, 255, 255));
        lblHost.setText("Host");

        lblUsuario.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");

        lblContrasena.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contrasena");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtHost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHostKeyPressed(evt);
            }
        });

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        txtContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContrasenaKeyPressed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("MOAM91", 0, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        btnSalir.setText("Salir ");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exithover.png"))); // NOI18N
        btnSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exithover.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lbPuerto.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lbPuerto.setForeground(new java.awt.Color(255, 255, 255));
        lbPuerto.setText("Puerto");

        txtPuerto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPuertoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPuerto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContrasena)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHost))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtContrasena)
                                    .addComponent(txtPuerto)
                                    .addComponent(txtHost))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblHost)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPuerto)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabBD.addTab("Base de Datos", jPanel1);

        jPanel2.setToolTipText("Aqui se restaura la base de datos");

        txtArchivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArchivoKeyPressed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restuarar");
        btnRestaurar.setEnabled(false);
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un Archivo sql para restuarar la base de datos");

        btnSalir2.setText("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRestaurar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnSalir2))
        );

        tabBD.addTab("Restaurar BD", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel3.setToolTipText("Aqui se realizan los respaldos de la base de datos");
        jPanel3.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Coloque la ruta en donde quiere hacer el respaldo");

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        btnGuardar2.setText("Guardar");
        btnGuardar2.setEnabled(false);
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });

        btnSalir3.setText("Salir");
        btnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar1))
                    .addComponent(btnGuardar2)
                    .addComponent(jLabel2))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnSalir3))
        );

        tabBD.addTab("Respaldos BD", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabBD)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabBD, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabBD.getAccessibleContext().setAccessibleName("BD");
        tabBD.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
       VALIDACION.Validacion valid = new Validacion();

        if(evt.getKeyCode() == evt.VK_ENTER){
            this.txtHost.requestFocus();
            
        }
        if(!valid.campos(lcampos) || this.txtNombre.getText().equalsIgnoreCase("")){
            this.btnGuardar.setEnabled(false);
        }else if(valid.campos(lcampos)){
            this.btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtHostKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHostKeyPressed
        // TODO add your handling code here:
        VALIDACION.Validacion valid = new Validacion();

        if(evt.getKeyCode() == evt.VK_ENTER){
            this.txtUsuario.requestFocus();
        }
        
        if(!valid.campos(lcampos) || this.txtHost.getText().equalsIgnoreCase("")){
            this.btnGuardar.setEnabled(false);
        }else if(valid.campos(lcampos)){
            this.btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_txtHostKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        // TODO add your handling code here:
        VALIDACION.Validacion valid = new Validacion();

        if(evt.getKeyCode() == evt.VK_ENTER)
            this.txtContrasena.requestFocus();
        
        if(!valid.campos(lcampos) || this.txtUsuario.getText().equalsIgnoreCase("")){
            this.btnGuardar.setEnabled(false);
        }else if(valid.campos(lcampos)){
            this.btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtContrasenaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContrasenaKeyPressed
        // TODO add your handling code here:
        VALIDACION.Validacion valid = new Validacion();

        if(evt.getKeyCode() == evt.VK_ENTER){
            this.Guardar();
        }
        if(valid.campos(lcampos)){
            this.btnGuardar.setEnabled(true);
        }
        if(!valid.campos(lcampos)) {
            this.btnGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_txtContrasenaKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here
            this.Guardar();
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPuertoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoKeyPressed
        // TODO add your handling code here:}
         VALIDACION.Validacion valid = new Validacion();

        if(evt.getKeyCode() == evt.VK_ENTER)
            this.txtUsuario.requestFocus();
        
        if(!valid.campos(lcampos) || this.txtPuerto.getText().equalsIgnoreCase("")){
            this.btnGuardar.setEnabled(false);
        }else if(valid.campos(lcampos)){
            this.btnGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_txtPuertoKeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Saliendo de la ventana configuracion");
    
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        JFileChooser Selector = new JFileChooser();
        Selector.showOpenDialog(this);
        File Archivo = Selector.getSelectedFile();
        if(Archivo != null){
            this.txtArchivo.setText(Archivo.getAbsolutePath());
            this.btnRestaurar.setEnabled(true);
        }
        else{
            this.btnRestaurar.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArchivoKeyPressed
        // TODO add your handling code here:
        if(this.txtArchivo.getText().equalsIgnoreCase("") || this.txtArchivo.getText().length() == 0)
            this.btnRestaurar.setEnabled(false);
        else
            this.btnRestaurar.setEnabled(true);
        if(evt.getKeyCode() == evt.VK_ENTER && this.txtArchivo.getText().length() > 0)
            this.restaurar();
            
    }//GEN-LAST:event_txtArchivoKeyPressed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        // TODO add your handling code here:
        this.restaurar();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        JFileChooser Selector = new JFileChooser();
        Selector.showSaveDialog(this);
        File Archivo = Selector.getSelectedFile();
        if(Archivo != null){
            this.txtArchivo1.setText(Archivo.getAbsolutePath());
            this.btnGuardar2.setEnabled(true);
        }
        else{
            this.btnGuardar2.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalir3ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
        this.guardarArchivo();
    }//GEN-LAST:event_btnGuardar2ActionPerformed

  public void SNumeros (JTextField a)
    {
        a.addKeyListener(new KeyAdapter()
        {
            public void keyTyped( KeyEvent e)
            {
                char c=e. getKeyChar();
                if(!Character.isDigit(c))
                {
                    getToolkit().beep();;
                    e.consume();
                }
            }
        });
           
    }
     //METODO PARA VALIDAR QUE LA ENTRADA DE DATOS A LAS CASILLAS DE TEXTOS SEA SOLO LETRAS   
  
    public void SLetras (JTextField a)
    {
        a.addKeyListener(new KeyAdapter()
        {
            public void keyTyped( KeyEvent e)
            {
                char c=e. getKeyChar();
                if(Character.isDigit(c) || !Character.isAlphabetic(c))
                {
                    getToolkit().beep();;
                    e.consume();
                }
            }
        });
    }
     /**
     * Metodo Guardar
     * Este se encargar de crear un archivo llamado config.txt que va a contener toda la configuracion de 
     * la conexion de la base de datos, esta informacion las obtiene de los campos de la ventana.
     */
    private void Guardar(){
        try {
        Config = new Formatter("config.txt");
        } catch( SecurityException securityException ){
            JOptionPane.showMessageDialog(null, "No tiene permisos para guardar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.SEVERE, "Error de lectura y escritura de datos: {0}", securityException.getMessage());

        }catch (FileNotFoundException fileNotFound){
            JOptionPane.showMessageDialog(null, "Error al guardar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.WARNING, "Error de acceso a archivo: {0}", fileNotFound.getMessage());

        }
        
        String nombre, host, puerto, usuario, contrasena;
        
        nombre = txtNombre.getText();
        host = txtHost.getText();
        puerto = txtPuerto.getText();
        usuario = txtUsuario.getText();
        contrasena = txtContrasena.getText();
        
        try{
            Config.format("%s\n%s\n%s\n%s\n%s", nombre, host, puerto, usuario, contrasena);
        }catch(FormatterClosedException formatClose){
            JOptionPane.showMessageDialog(null, "Error al guardar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.WARNING, "Error al guardar la configuracion: {0}", formatClose.getMessage());

        }
        
        Config.close();
        
     
        JOptionPane.showMessageDialog(null, "Guardado", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Ha guardado informacion");

     
    }
     /**
     * Metodo Leer
     * Este metodo se encargar de leer la configuracion de la base de datos del archivo config.txt,
     * y luego carga esta informacion en todos los campos de la ventana.
     */
    private void Leer(){
        try{
            entrada = new Scanner(new File("config.txt"));
        }catch( FileNotFoundException fileNotFound){
          JOptionPane.showMessageDialog(null, "Error al cargar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
           BitacoraVentanas.LOG_RAIZ.log(Level.SEVERE, "Error en lectura de configuracion: {0}", fileNotFound.getMessage());


        }
        
        while(entrada.hasNext()){
                txtNombre.setText(entrada.next());
                txtHost.setText(entrada.next());
                txtPuerto.setText(entrada.next());
                txtUsuario.setText(entrada.next());
                try{
                    txtContrasena.setText(entrada.next());
                }catch(NoSuchElementException noElement){
                    txtContrasena.setText("");
                    BitacoraVentanas.LOG_RAIZ.log(Level.WARNING, "Base de datos sin contraseña: {0}", noElement.getMessage());

                }
        }
        entrada.close();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton btnSalir3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbPuerto;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblHost;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTabbedPane tabBD;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtArchivo1;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTextField[] lcampos = new javax.swing.JTextField[4];

    private void restaurar() {
        Respaldo Restaurar = new Respaldo(this.txtArchivo.getText());
        Restaurar.Restuarar();
    }

    private void guardarArchivo() {
        Respaldo Guardar = new Respaldo(this.txtArchivo1.getText());
        Guardar.Respaldar();
    }

}
