/*
 * Copyright 2019 yorlysoro <yorlysoro@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package luncheria;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana ConsultaFactCliente
 * Se encargar de mostrar la informacion de los clientes que van a hacer cargados en la factura,
 * el usuario selecciona en la tabla uno de los clientes, y su informacion es enviada a la ventana padre
 * por medio del metodo setCod, pasandole como parametro la cedula del cliente.
 * @author Jerrinson
 */
public class ConsultaFactCliente extends javax.swing.JDialog {
      private basedatos bd;
    private factura fact;
    private DefaultTableModel tabla; 
    private String nomb_user;
    private String cod_user;
    /**
     * Creates new form ConsultaFactCliente
     */
    /**
     * Constructor ConsultaFactCliente
     * Recibe como parametro El padre, el modal, la base de datos, la factura, el nombre de usuario, y el codigo de usuario
     * @param parent
     * @param modal
     * @param bd
     * @param fact
     * @param nomb_user
     * @param cod_user 
     */
    public ConsultaFactCliente(java.awt.Frame parent, boolean modal,basedatos bd, factura fact, String nomb_user, String cod_user ) {
        super(parent, modal);
        BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Inciando la ventana consultar clientes");

       this.bd = bd;
        this.fact = fact;
        this.nomb_user = nomb_user;
        this.cod_user = cod_user;
        initComponents();
        this.setLocationRelativeTo(null);
        this.tabla =(DefaultTableModel) tablaClientes.getModel();
        this.Cargar_Tabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        JBtn_aceptar = new javax.swing.JButton();
        JBtn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Clientes");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        tablaClientes.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Telefono"
            }
        ));
        tablaClientes.setToolTipText("");
        tablaClientes.setGridColor(new java.awt.Color(51, 51, 255));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        JBtn_aceptar.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_aceptar.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/274-checkmark2hover.png"))); // NOI18N
        JBtn_aceptar.setText("ACEPTAR");
        JBtn_aceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_aceptar.setEnabled(false);
        JBtn_aceptar.setFocusPainted(false);
        JBtn_aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/274-checkmark2.png"))); // NOI18N
        JBtn_aceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/274-checkmark2.png"))); // NOI18N
        JBtn_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_aceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_aceptarMouseExited(evt);
            }
        });
        JBtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_aceptarActionPerformed(evt);
            }
        });

        JBtn_salir.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_salir.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_salir.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        JBtn_salir.setText("     SALIR");
        JBtn_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_salir.setFocusPainted(false);
        JBtn_salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exithover.png"))); // NOI18N
        JBtn_salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exithover.png"))); // NOI18N
        JBtn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_salirMouseExited(evt);
            }
        });
        JBtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(JBtn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:
        this.JBtn_aceptar.setEnabled(true);
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void JBtn_aceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_aceptarMouseEntered
        JBtn_aceptar.setBackground( new Color(255,255,255));
        JBtn_aceptar.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_aceptarMouseEntered

    private void JBtn_aceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_aceptarMouseExited
        JBtn_aceptar.setBackground( new Color(51,102,255));
        JBtn_aceptar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_aceptarMouseExited

    private void JBtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_aceptarActionPerformed
        this.aceptar();
    }//GEN-LAST:event_JBtn_aceptarActionPerformed

    private void JBtn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_salirMouseEntered
        // TODO add your handling code here:
        JBtn_salir.setBackground( new Color(255,255,255));
        JBtn_salir.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_salirMouseEntered

    private void JBtn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_salirMouseExited
        // TODO add your handling code here:
        JBtn_salir.setBackground( new Color(51,102,255));
        JBtn_salir.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_salirMouseExited

    private void JBtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_salirActionPerformed
        BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Saliendo de la ventana clientes");

        this.dispose();
    }//GEN-LAST:event_JBtn_salirActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_aceptar;
    private javax.swing.JButton JBtn_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
/**
     * Metodo Cargar_Tabla
     * Se encarga de cargar la tabla con la cedula, nombre, apellido, telefono de los clientes
     * que esten registrados en la base de datos.
     */
    private void Cargar_Tabla() {
    try{
            this.bd.Conectar();
            this.bd.setResult("SELECT cedula,nombres,apellidos,telefono FROM clientes WHERE status='1'");
            String Datos[] = new String[4];
            ResultSet result = this.bd.getResult();
            while(result.next()){
                Datos[0] = (""+result.getString(1));
                Datos[1] = (""+result.getString(2));
                Datos[2] = (""+result.getString(3));
                Datos[3] = (""+result.getString(4));
                this.tabla.addRow(Datos);
            }
        }catch (SQLException ex) {
                BitacoraVentanas.LOG_RAIZ.log(Level.CONFIG, "Error al cargar la tabla desde la base de datos:{0}", ex.getMessage());
            }
       
    }    
 /**
     *  Metodo aceptar
     * Pasa la cedula del cliente a la ventana padre, obtenido de la tabla
     * al metodo setCod.
     */
    private void aceptar() {
        if(this.tablaClientes.getSelectedRow() >= 0){
            this.fact.setCod(String.valueOf(this.tabla.getValueAt(this.tablaClientes.getSelectedRow(), 0)));
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila!!", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.WARNING, "Error al enviar datos a un ventana padre");

        }    }

   
}
