/*
 * Copyright 2019 yorlysoro <yorlysoro@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package luncheria;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Formatter;
import java.util.FormatterClosedException;
import java.util.logging.Level;
//import javafx.animation.Animation;
import javax.swing.JOptionPane;
/*import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
*/
/**
 *
 * @author Jerrinson
 */
public class New_menu extends javax.swing.JFrame {

    private basedatos bd;
    private String nombre_user;
    private String cod_nivel;
  
    
    
    public New_menu(String nombre_user, String cod_nivel, basedatos bd, String ced) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Iniciando el menu");

        this.nombre_user = nombre_user;
        this.cod_nivel = cod_nivel;
        this.bd = bd;
        this.asignarNombre(ced);
        this.setLocationRelativeTo(null);
        this.guardarCodUser(ced);
        this.verficarUsuario(cod_nivel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBtn_factura = new javax.swing.JButton();
        JBtn_cliente = new javax.swing.JButton();
        JPanel_Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JBtn_Menu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JLabel_user = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        JBtn_Menu1 = new javax.swing.JButton();
        JBtn_reportes = new javax.swing.JButton();
        JBtn_inventario = new javax.swing.JButton();
        JBtn_mClientes = new javax.swing.JButton();
        JBtn_mUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LUNCHERIA NORA");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtn_factura.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_factura.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_factura.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fact_ico.png"))); // NOI18N
        JBtn_factura.setText("     FACTURA");
        JBtn_factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_factura.setEnabled(false);
        JBtn_factura.setFocusPainted(false);
        JBtn_factura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fact_icohover.png"))); // NOI18N
        JBtn_factura.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fact_icohover.png"))); // NOI18N
        JBtn_factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_facturaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_facturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_facturaMouseExited(evt);
            }
        });
        JBtn_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_facturaActionPerformed(evt);
            }
        });
        jPanel1.add(JBtn_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 240, 100));

        JBtn_cliente.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_cliente.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_cliente.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/116-user-plus.png"))); // NOI18N
        JBtn_cliente.setText("NUEVO CLIENTE");
        JBtn_cliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_cliente.setEnabled(false);
        JBtn_cliente.setFocusPainted(false);
        JBtn_cliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/116-user-plushover.png"))); // NOI18N
        JBtn_cliente.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/116-user-plushover.png"))); // NOI18N
        JBtn_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_clienteMouseExited(evt);
            }
        });
        JBtn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(JBtn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 240, 100));

        JPanel_Menu.setBackground(new java.awt.Color(255, 255, 255));
        JPanel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/585e4bf3cb11b227491c339a.png"))); // NOI18N
        JPanel_Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 138, 114));

        jLabel3.setFont(new java.awt.Font("MOAM91", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALIR DEL SISTEMA");
        JPanel_Menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 140, 26));

        JBtn_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/190-menu.png"))); // NOI18N
        JBtn_Menu.setBorderPainted(false);
        JBtn_Menu.setContentAreaFilled(false);
        JBtn_Menu.setFocusPainted(false);
        JBtn_Menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/190-menuhover.png"))); // NOI18N
        JBtn_Menu.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/190-menuhover.png"))); // NOI18N
        JBtn_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_MenuMouseClicked(evt);
            }
        });
        JBtn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_MenuActionPerformed(evt);
            }
        });
        JPanel_Menu.add(JBtn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 57, 41));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exit.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exithover.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/277-exithover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanel_Menu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 50, 50));

        JLabel_user.setFont(new java.awt.Font("MOAM91", 0, 12)); // NOI18N
        JLabel_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPanel_Menu.add(JLabel_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 270, 30));

        jButton2.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton2.setText("CAMBIAR USUARIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        JPanel_Menu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 270, 50));

        jButton3.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton3.setText("NUEVO USUARIO");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        JPanel_Menu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 50));

        jButton4.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton4.setText("CONFIGURACIÓN");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        JPanel_Menu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 270, 50));

        jButton5.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton5.setText("NUEVOS SERVICIOS");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        JPanel_Menu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, 50));

        jPanel1.add(JPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 1, -1, 800));

        JBtn_Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/190-menu.png"))); // NOI18N
        JBtn_Menu1.setBorderPainted(false);
        JBtn_Menu1.setContentAreaFilled(false);
        JBtn_Menu1.setFocusPainted(false);
        JBtn_Menu1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/190-menuhover.png"))); // NOI18N
        JBtn_Menu1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/190-menuhover.png"))); // NOI18N
        JBtn_Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_Menu1MouseClicked(evt);
            }
        });
        jPanel1.add(JBtn_Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 11, 57, 40));

        JBtn_reportes.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_reportes.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_reportes.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fact_ico.png"))); // NOI18N
        JBtn_reportes.setText("     REPORTES");
        JBtn_reportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_reportes.setFocusPainted(false);
        JBtn_reportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fact_icohover.png"))); // NOI18N
        JBtn_reportes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fact_icohover.png"))); // NOI18N
        JBtn_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_reportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_reportesMouseExited(evt);
            }
        });
        JBtn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_reportesActionPerformed(evt);
            }
        });
        jPanel1.add(JBtn_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 240, 100));

        JBtn_inventario.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_inventario.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_inventario.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/059-carrito.png"))); // NOI18N
        JBtn_inventario.setText("     INVENTARIO");
        JBtn_inventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_inventario.setEnabled(false);
        JBtn_inventario.setFocusPainted(false);
        JBtn_inventario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/059-carritohover.png"))); // NOI18N
        JBtn_inventario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/059-carritohover.png"))); // NOI18N
        JBtn_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_inventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_inventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_inventarioMouseExited(evt);
            }
        });
        JBtn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_inventarioActionPerformed(evt);
            }
        });
        jPanel1.add(JBtn_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 240, 100));

        JBtn_mClientes.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_mClientes.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_mClientes.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_mClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/115-usuario.png"))); // NOI18N
        JBtn_mClientes.setText("    CLIENTES");
        JBtn_mClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_mClientes.setEnabled(false);
        JBtn_mClientes.setFocusPainted(false);
        JBtn_mClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/115-usuariohover.png"))); // NOI18N
        JBtn_mClientes.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/115-usuariohover.png"))); // NOI18N
        JBtn_mClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_mClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_mClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_mClientesMouseExited(evt);
            }
        });
        JBtn_mClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_mClientesActionPerformed(evt);
            }
        });
        jPanel1.add(JBtn_mClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 240, 100));

        JBtn_mUsuario.setBackground(new java.awt.Color(51, 102, 255));
        JBtn_mUsuario.setFont(new java.awt.Font("MOAM91", 1, 14)); // NOI18N
        JBtn_mUsuario.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_mUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/115-usuario.png"))); // NOI18N
        JBtn_mUsuario.setText("    USUARIOS");
        JBtn_mUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.white, java.awt.Color.white));
        JBtn_mUsuario.setEnabled(false);
        JBtn_mUsuario.setFocusPainted(false);
        JBtn_mUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/115-usuariohover.png"))); // NOI18N
        JBtn_mUsuario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/115-usuariohover.png"))); // NOI18N
        JBtn_mUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_mUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBtn_mUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBtn_mUsuarioMouseExited(evt);
            }
        });
        JBtn_mUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_mUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(JBtn_mUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 240, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_facturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_facturaMouseEntered
        JBtn_factura.setBackground( new Color(255,255,255));
        JBtn_factura.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_facturaMouseEntered

    private void JBtn_facturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_facturaMouseExited
        JBtn_factura.setBackground( new Color(51,102,255));
        JBtn_factura.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_facturaMouseExited

    private void JBtn_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_clienteMouseEntered
        JBtn_cliente.setBackground( new Color(255,255,255));
        JBtn_cliente.setForeground(new Color(0,0,0));

    }//GEN-LAST:event_JBtn_clienteMouseEntered

    private void JBtn_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_clienteMouseExited
        JBtn_cliente.setBackground( new Color(51,102,255));
        JBtn_cliente.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_clienteMouseExited

    private void JBtn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_clienteActionPerformed
        new clientes(bd, this.nombre_user, this.cod_nivel).setVisible(true);
    }//GEN-LAST:event_JBtn_clienteActionPerformed

    private void JBtn_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_facturaActionPerformed
        new factura(bd, nombre_user, cod_nivel).setVisible(true);
        
    }//GEN-LAST:event_JBtn_facturaActionPerformed

    private void JBtn_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_MenuMouseClicked
        Animacion.Animacion.mover_derecha(1100, 1500, 10, 5, JPanel_Menu);
       
    }//GEN-LAST:event_JBtn_MenuMouseClicked

    private void JBtn_Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_Menu1MouseClicked
        Animacion.Animacion.mover_izquierda(1500, 1060, 10, 5, JPanel_Menu);
    }//GEN-LAST:event_JBtn_Menu1MouseClicked

    private void JBtn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_MenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int mj= JOptionPane.YES_NO_OPTION;
            int mensaje= JOptionPane.showConfirmDialog(this, "¿Realmente desea salir?","Salir",mj);
        if (mensaje == 0) {
           BitacoraVentanas.LOG_RAIZ.log(Level.INFO, "Saliendo del menu");

            System.exit(0);
            this.setState(New_A.ICONIFIED);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBtn_facturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_facturaMouseClicked
            //new factura(bd, nombre_user, cod_nivel).setVisible(true);
    }//GEN-LAST:event_JBtn_facturaMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            new servicio(bd, this.nombre_user, this.cod_nivel).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new cajeros(bd, this.nombre_user, this.cod_nivel).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            new Configuracion().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            this.dispose();
            new New_A().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JBtn_reportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_reportesMouseClicked
        
    }//GEN-LAST:event_JBtn_reportesMouseClicked

    private void JBtn_reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_reportesMouseEntered
        JBtn_reportes.setBackground( new Color(255,255,255));
        JBtn_reportes.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_reportesMouseEntered

    private void JBtn_reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_reportesMouseExited
        JBtn_reportes.setBackground( new Color(51,102,255));
        JBtn_reportes.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_reportesMouseExited

    private void JBtn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_reportesActionPerformed
        new Reportes_new(this.bd, this.nombre_user, this.cod_nivel).setVisible(true);
    }//GEN-LAST:event_JBtn_reportesActionPerformed

    private void JBtn_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_inventarioMouseClicked
        
    }//GEN-LAST:event_JBtn_inventarioMouseClicked

    private void JBtn_inventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_inventarioMouseEntered
        JBtn_inventario.setBackground( new Color(255,255,255));
        JBtn_inventario.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_inventarioMouseEntered

    private void JBtn_inventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_inventarioMouseExited
        JBtn_inventario.setBackground( new Color(51,102,255));
        JBtn_inventario.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_inventarioMouseExited

    private void JBtn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_inventarioActionPerformed
        // TODO add your handling code here:
        new inventario(bd).setVisible(true);
    }//GEN-LAST:event_JBtn_inventarioActionPerformed

    private void JBtn_mClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_mClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_mClientesMouseClicked

    private void JBtn_mClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_mClientesMouseEntered
         JBtn_mClientes.setBackground( new Color(255,255,255));
         JBtn_mClientes.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_mClientesMouseEntered

    private void JBtn_mClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_mClientesMouseExited
        JBtn_mClientes.setBackground( new Color(51,102,255));
        JBtn_mClientes.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_mClientesMouseExited

    private void JBtn_mClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_mClientesActionPerformed
        // TODO add your handling code here:
        new vtnclientes(bd).setVisible(true);
    }//GEN-LAST:event_JBtn_mClientesActionPerformed

    private void JBtn_mUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_mUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_mUsuarioMouseClicked

    private void JBtn_mUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_mUsuarioMouseEntered
         JBtn_mUsuario.setBackground( new Color(255,255,255));
         JBtn_mUsuario.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JBtn_mUsuarioMouseEntered

    private void JBtn_mUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_mUsuarioMouseExited
        JBtn_mUsuario.setBackground( new Color(51,102,255));
        JBtn_mUsuario.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_JBtn_mUsuarioMouseExited

    private void JBtn_mUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_mUsuarioActionPerformed
        // TODO add your handling code here:
        new usuarios(bd).setVisible(true);
    }//GEN-LAST:event_JBtn_mUsuarioActionPerformed

        // METODO QUE ME MUESTRA REPORTE DE VENTAS REALIZADO EN IREPORT
    private void reporVenta() {
        
        basedatos bd = new basedatos();
        bd.Conectar();
        basedatos mysql = new basedatos();
        java.sql.Connection con= mysql.Conectar();  
             
   
       try{
   
         String ubicacion = System.getProperty("user.dir")+"/src/reportes/venta.jasper";
    
//      JasperReport jasperReport=(JasperReport) JRLoader.loadObject(ubicacion);
      
    
            
//      JasperPrint prin = JasperFillManager.fillReport(jasperReport,null,con);
     
//      JasperViewer viw= new JasperViewer (prin,false);
      
  //    viw.setVisible(true);
    
       } catch (Exception ex) {
    }  
    
    
    }

    // METODO QUE ME MUESTRA REPORTE DE USUARIOS REALIZADO EN IREPORT

    private void reporUsuario() {

     basedatos bd = new basedatos();
        bd.Conectar();
        basedatos mysql = new basedatos();
        java.sql.Connection con= mysql.Conectar();  
             
   
       try{
   
         String ubicacion = System.getProperty("user.dir")+"/src/reportes/usuario.jasper";
    
//      JasperReport jasperReport=(JasperReport) JRLoader.loadObject(ubicacion);
      
    
            
//      JasperPrint prin = JasperFillManager.fillReport(jasperReport,null,con);
     
  //    JasperViewer viw= new JasperViewer (prin,false);
      
    //  viw.setVisible(true);
    
       } catch (Exception ex) {
    }
    
    }
    // METODO QUE ME MUESTRA REPORTE DE SERVICIOS REALIZADO EN IREPORT

    private void reporServ() {
        
    basedatos bd = new basedatos();
        bd.Conectar();
        basedatos mysql = new basedatos();
        java.sql.Connection con= mysql.Conectar();  
             
   
       try{
   
         String ubicacion = System.getProperty("user.dir")+"/src/reportes/servicio.jasper";
    
//      JasperReport jasperReport=(JasperReport) JRLoader.loadObject(ubicacion);
      
    
            
  //    JasperPrint prin = JasperFillManager.fillReport(jasperReport,null,con);
     
    //  JasperViewer viw= new JasperViewer (prin,false);
      
      //viw.setVisible(true);
    
       } catch (Exception ex) {
    }
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Menu;
    private javax.swing.JButton JBtn_Menu1;
    private javax.swing.JButton JBtn_cliente;
    private javax.swing.JButton JBtn_factura;
    private javax.swing.JButton JBtn_inventario;
    private javax.swing.JButton JBtn_mClientes;
    private javax.swing.JButton JBtn_mUsuario;
    private javax.swing.JButton JBtn_reportes;
    private javax.swing.JLabel JLabel_user;
    private javax.swing.JPanel JPanel_Menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void asignarNombre(String ced) {
        try{
            this.bd.Conectar();
            this.bd.setResult("SELECT nombres, apellidos FROM empleados WHERE cedula = '" + ced + "'");
            ResultSet result =  this.bd.getResult();
            while(result.next()){
                this.JLabel_user.setText(""+ result.getString(1) + " " + result.getString(2) );
            }
        } catch (SQLException ex){
            
        }
    }

    private void guardarCodUser(String ced) {
        Formatter Config = null;
        try {
            Config = new Formatter("cod_user.txt");
        } catch( SecurityException securityException ){
            JOptionPane.showMessageDialog(null, "No tiene permisos para guardar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.SEVERE, "Error de lectura y escritura de datos: {0}", securityException.getMessage());

        }catch (FileNotFoundException fileNotFound){
            JOptionPane.showMessageDialog(null, "Error al guardar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.WARNING, "Error de acceso a archivo: {0}", fileNotFound.getMessage());

        }
          try{
            Config.format("%s\n", ced);
        }catch(FormatterClosedException formatClose){
            JOptionPane.showMessageDialog(null, "Error al guardar la configuracion", "Error", JOptionPane.ERROR_MESSAGE);
            BitacoraVentanas.LOG_RAIZ.log(Level.WARNING, "Error al guardar la configuracion: {0}", formatClose.getMessage());

        }
        
        Config.close();
    }

    private void verficarUsuario(String cod_nivel) {
        if(cod_nivel.equalsIgnoreCase("2")){
            this.JBtn_mClientes.setEnabled(true);
            this.JBtn_factura.setEnabled(true);
            this.JBtn_cliente.setEnabled(true);
            
        } else if(cod_nivel.equalsIgnoreCase("3")){
            this.JBtn_inventario.setEnabled(true);
            this.jButton5.setEnabled(true);
        } else {
            this.JBtn_mClientes.setEnabled(true);
            this.JBtn_factura.setEnabled(true);
            this.JBtn_cliente.setEnabled(true);
            this.JBtn_inventario.setEnabled(true);
            this.jButton5.setEnabled(true);
            this.JBtn_mUsuario.setEnabled(true);
            this.jButton3.setEnabled(true);
            this.jButton4.setEnabled(true);
        }
    }
}

